export default [
  { className: 'LoadingScene', class: require('../class/LoadingScene.js').default },
  { className: 'TitleScene', class: require('../class/TitleScene.js').default },
  { className: 'GameScene', class: require('../class/GameScene.js').default },
  { className: 'Mission', class: require('../class/Mission.js').default },
  { className: 'Tile', class: require('../class/Tile.js').default },
  { className: 'SlicedSprite', class: require('../class/SlicedSprite.js').default },
  { className: 'Piece', class: require('../class/Piece.js').default },
  { className: 'BlurLabel', class: require('../class/BlurLabel.js').default },
  { className: 'Camera', class: require('../class/Camera.js').default },
  { className: 'InterfaceScreen', class: require('../class/InterfaceScreen.js').default },
  { className: 'InterfaceField', class: require('../class/InterfaceField.js').default },
  { className: 'FlyingElement', class: require('../class/FlyingElement.js').default },
  { className: 'Player', class: require('../class/Player.js').default },
  { className: 'Computer', class: require('../class/Computer.js').default },
  { className: 'Laser', class: require('../class/Laser.js').default },
  { className: 'MissionSelect', class: require('../class/MissionSelect.js').default },
  { className: 'MissionSelectItem', class: require('../class/MissionSelectItem.js').default },
  { className: 'Explosion', class: require('../class/Explosion.js').default }
]
